### ISSUE TITLE
Interest in improved adaptive icon?

### ISSUE THREAD

**Issue by He-Ro** [bpellin/keepassdroid#313]
Hello,

first thanks for the awesome app! It is my goto Keepass app on Android.
This issue is more a question about the launcher icon. I saw that in version 2.3.1 support for adaptive icons was introduced.
But it looks like the round icon is just plastered on the background, that then has the desired shape:
![screenshot_20180814-195531](https://user-images.githubusercontent.com/3579374/44109195-b443d736-9ffc-11e8-8059-5e2091857f6f.png)
The other icons look much more elegant and play nicely with the reshaping.
So I am asking whether you would be interested in redesigning the app icon with adaptive icons in mind.
I had a quick try, which you can see here [adaptive mockup](https://adapticon.tooo.io/#/bg=https://ptpb.pw/nGlm.png/fg=https://ptpb.pw/Kczd.png) in action.
Here is the mochup in the same shape as in the screenshot:
![screenshot-selection-2018-08-14-20 05 45](https://user-images.githubusercontent.com/3579374/44109497-843aff0a-9ffd-11e8-8cd0-ef3a821146a5.png)

Of course this is just an idea, if you do not like it, then that's okay with me, I at least wanted to try and offer to help. Also the my new design is just a mockup and I am open for any improvements! Since I am not a designer it surely could be improved ;)

**Comment by mattcoxonline** [comment]
I agree with this. I use the app daily and the design is something that irks me. Improving the icon would be a start. @He-Ro has a good suggestion. Maybe boost the contrast in the colours a little though and run with a white icon and brighter purple bg.

![sep-17-2018 16-39-30](https://user-images.githubusercontent.com/673542/45630132-534ab380-ba98-11e8-9d37-5e605fd2f56c.gif)

[Adaptive Mockup](https://adapticon.tooo.io/#/bg=https://user-images.githubusercontent.com/673542/45629839-9c4e3800-ba97-11e8-8a4c-b93124990c29.png/fg=https://user-images.githubusercontent.com/673542/45629840-9c4e3800-ba97-11e8-8a02-8557c35bc8c5.png)

**Comment by shvmm** [comment]
I also made mockups of improved adaptive icons for KeePass.
![rect3717](https://user-images.githubusercontent.com/54358380/67147444-773b8280-f2b2-11e9-972f-f70914df7894.png)
![bitmap](https://user-images.githubusercontent.com/54358380/67147448-799ddc80-f2b2-11e9-90ea-4274efce2503.png)

**Comment by bpellin** [comment]
@shvmm I like these. I'll try to switch to the purpleish one.

**Comment by mattcoxonline** [comment]
@bpellin Not sure which you're referring to when you say "the purpleish one" but if you pick anything with a solid circle around it, it's not going to work. 

The whole point of the adaptive icon is so that it can adapt to different shapes that different OEMs put on their build of the OS.

If you pick something that has a circle, it's still going to look like the first screenshot from @He-Ro 🤷‍♂️

**Comment by shvmm** [comment]
"The overall square is 108dp and the outermost gray circle is 66dp in 'diameter'...  " The overall image is 1728x1728 pixels (16x). I think it's easy to create both foreground (set white to alpha?) and background mask from the given image. I'm not well versed with android SDK otherwise I'd provided it myself.

**Comment by shvmm** [comment]
[drawing.zip](https://github.com/bpellin/keepassdroid/files/4221467/drawing.zip)
![purplr](https://user-images.githubusercontent.com/54358380/74773862-b60d3380-52b8-11ea-8746-a6569b19f126.png)
@bpellin Extremely sorry for not providing the sources. Here they are in public domain.
