### ISSUE TITLE
"Fingerprint problem" with Pixel 3 after Android 10 upgrade

### ISSUE THREAD

**Issue by MassMediocrity** [bpellin/keepassdroid#369]
The message "Fingerprint problem" now appears each time I open the app and the app has stopped responding to the fingerprint scanner on my Pixel 3 following the update to Android 10.

**Comment by richardeid** [comment]
I had this problem and what I did to correct it was to open the app and enter my password manually. Instead of pressing enter, leave the password there and touch your fingerprint sensor. It started working for me after this.

Also, when the problem first started I had cleared the app cache and storage. Not sure if that's necessary, but if there above doesn't work then I guess you can try clearing cache and storage.

**Comment by MassMediocrity** [comment]
This, as well as several other apps I couldn't use a fingerprint scan for, started working after the last security patch. As mentioned above, I still had to clear storage to get it going again.
