### ISSUE TITLE
Failed to Store Database 

### ISSUE THREAD

**Issue by twar76** [bpellin/keepassdroid#422]
I am getting an error message "Failed to store database " when trying to save a change.  This seems to occur after the new update for the Android version.

**Comment by bpellin** [comment]
The latest version makes a change that tells the content provider application to truncate the file upon opening. Prior to doing this, so .kdb databases would get corrupted when you make a change that makes the database smaller, because some content providers would not shrink the file size when you reduce the database size.

It's possible some content providers are not compatible with this.

What app are you using to provide the file for the database?

What version of Android does your phone have?

What's the URL for the file you are opening? You should see something like content://com.something.something/...

**Comment by twar76** [comment]
I am running Android 10 on my Galaxy S9.

I am storing the database and key on my Google drive account.  I can open
it without any issues but it won't let me save any new changes.

**Comment by bpellin** [comment]
Fixed in 2.5.14.
